### ISSUE TITLE
Long dev docs title in nav bar on mobile needs css override for default theme

### ISSUE THREAD

**Issue by imylomylo** [KomodoPlatform/developer-docs#1]
```css
@media (max-width: 419px){ 

//nav bar, default is 3.6rem
  .navbar {
    height: 5.0rem;
  }

//side bar top heading loses spacing, default is 0.5rem on first co-ordinate
  .sidebar .nav-links .nav-item {
    padding: 1.5rem 0 0.5rem 1.5rem;
  }

// top heading of main page loses spacing, default is -1.5rem
  .content:not(.custom) > h1:first-child, .content:not(.custom) > h2:first-child, .content:not(.custom) > h3:first-child, .content:not(.custom) > h4:first-child, .content:not(.custom) > h5:first-child, .content:not(.custom) > h6:first-child {
margin-top: -0.5rem;
  }
}
```
