### ISSUE TITLE
hero image on mobile, not scaling

### ISSUE THREAD

**Issue by imylomylo** [KomodoPlatform/developer-docs#2]
```css
@media (max-width: 419px){ 
//hero image, default is 210px & auto 
  .home .hero img {
    max-height: 100%;
    max-width: 100%;
  }
```
